name: Daily Learning Contribution

on:
  schedule:
    # Multiple commits throughout the day to look natural
    - cron: "30 8 * * *"   # 8:30 AM UTC (Morning learning)
    - cron: "0 13 * * *"   # 1:00 PM UTC (Lunch break learning)
    - cron: "30 17 * * *"  # 5:30 PM UTC (Evening review)
    - cron: "0 21 * * *"   # 9:00 PM UTC (Night practice)
  workflow_dispatch:

jobs:
  daily-learning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate learning content
        run: |
          # Create logs directory first
          mkdir -p logs
          
          # Create or append to daily log
          DATE=$(date +%Y-%m-%d)
          TIME=$(date +%H:%M)
          DAY=$(date +%A)
          
          # Create learning log entry
          echo "# Daily Learning Log - $DATE" > "logs/$DATE.md"
          echo "" >> "logs/$DATE.md"
          echo "## 📅 $DAY Learning Session - $TIME UTC" >> "logs/$DATE.md"
          echo "" >> "logs/$DATE.md"
          
          # Random learning activities to make it look natural
          ACTIVITIES=(
            "Reviewed Python data structures and algorithms"
            "Practiced SQL query optimization techniques"
            "Studied financial modeling best practices"
            "Explored machine learning concepts and applications"
            "Reviewed Power BI dashboard design principles"
            "Practiced Excel VBA automation techniques"
            "Studied cloud computing architecture patterns"
            "Reviewed statistical analysis methods"
            "Explored data visualization best practices"
            "Practiced coding interview problems"
          )
          
          # Pick random activities
          ACTIVITY1=${ACTIVITIES[$RANDOM % ${#ACTIVITIES[@]}]}
          ACTIVITY2=${ACTIVITIES[$RANDOM % ${#ACTIVITIES[@]}]}
          
          echo "### 🎯 Today's Focus:" >> "logs/$DATE.md"
          echo "- $ACTIVITY1" >> "logs/$DATE.md"
          echo "- $ACTIVITY2" >> "logs/$DATE.md"
          echo "- Maintained consistent learning momentum" >> "logs/$DATE.md"
          echo "" >> "logs/$DATE.md"
          echo "### 📈 Progress Notes:" >> "logs/$DATE.md"
          echo "- Continuing professional development journey" >> "logs/$DATE.md"
          echo "- Building strong technical foundation" >> "logs/$DATE.md"
          echo "- Enhancing data analysis capabilities" >> "logs/$DATE.md"
          echo "" >> "logs/$DATE.md"
          echo "---" >> "logs/$DATE.md"
          echo "*Generated at $TIME UTC on $DATE*" >> "logs/$DATE.md"
          
          # Update main README with latest activity
          echo "# 📚 Daily Learning Journey" > README.md
          echo "" >> README.md
          echo "🎯 **Mission**: Building consistent learning habits and tracking my professional development journey." >> README.md
          echo "" >> README.md
          echo "## 📊 Recent Learning Activity" >> README.md
          echo "" >> README.md
          echo "**Last Updated**: $DATE at $TIME UTC" >> README.md
          echo "" >> README.md
          echo "### 🔥 Current Learning Streak: Building daily habits!" >> README.md
          echo "" >> README.md
          echo "### 📝 Latest Learning Session:" >> README.md
          echo "- $ACTIVITY1" >> README.md
          echo "- $ACTIVITY2" >> README.md
          echo "" >> README.md
          echo "## 🗂️ Learning Logs" >> README.md
          echo "" >> README.md
          echo "All daily learning activities are documented in the [logs/](./logs/) folder." >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "*🤖 This repository automatically tracks my daily learning activities*" >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "teslim@adeyanjuteslim.co.uk"
          git config --local user.name "Teslim Adeyanju"
          git add .
          
          # Create meaningful commit messages
          HOUR=$(date +%H)
          if [ $HOUR -lt 12 ]; then
            MESSAGE="🌅 Morning learning session - $(date +%Y-%m-%d)"
          elif [ $HOUR -lt 17 ]; then
            MESSAGE="☀️ Afternoon study session - $(date +%Y-%m-%d)"
          else
            MESSAGE="🌙 Evening learning review - $(date +%Y-%m-%d)"
          fi
          
          git commit -m "$MESSAGE" || echo "No changes to commit"
          git push
